### ISSUE TITLE
 No 'version' key in the manifest file for custom integration 'inkbird'

### ISSUE THREAD

**Issue by OJBender** [stelford/home-assistant_inkbird#9]
Hello, stellford. Thanks so much for the inkbird custom integration. Just stepped over a litte hiccup.
Can I just make up a version key" ?
Logger: homeassistant.loader
Source: loader.py:786

No 'version' key in the manifest file for custom integration 'inkbird'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'inkbird'

**Comment by kaijk** [comment]
@OJBender, some HA requirements/parameters have changed since your last commit.  I really want my inkbird to show in HA.

Please consider publishing this to HA's HACS as a quasi add-in.    

See [https://developers.home-assistant.io/docs/creating_integration_manifest/](url)

Also, how can I get past `test_btle.py`?  It's looking for info in /var/mail and can't find it, (its empty).
THX
